L2CacheConfig: { size: 1 MB, ways: 8, inclusive: true, banks: 4, tp: false, enableFlush: true }

EnablePowerDown: true

WFIResume: false

IMSICParams:
  imsicIntSrcWidth: 8
  mAddr: 0x3A800000
  sgAddr: 0x3B000000
  geilen: 7
  vgeinWidth: 6
  iselectWidth: 12
  EnableImsicAsyncBridge: true
  HasTEEIMSIC: false

EnableSramCtl: true
