name: Nightly Regression
on:
  schedule:
    # run at 15:33 UTC (23:33 UTC+8)
    - cron: '33 15 * * *'

jobs:
  performance-test:
    uses: ./.github/workflows/perf-template.yml
    with:
      test_branch: kunminghu-v3
      perf_report_dir: /nfs/home/cirunner/perf-report-nightly
      benchmark_type: spec06-0.3c
      servers: all
